ApsHgBrasilWeather/Models/ViewModels/PrevisaoTempoViewModel.cs
using ApsHgBrasilWeather.Models.RestModels.HgBrasil;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApsHgBrasilWeather.Models.ViewModels
{
    public class PrevisaoTempoViewModel
    {
        public PrevisaoTempoAtual PrevisaoTempoAtual { get; set; }

        [Display(Name = "Estado")]
        [Required(ErrorMessage = "Selecione um estado")]
        public string EstadoSelecionado { get; set; }

        public List<SelectListItem> Estados { get; set; }

        [Display(Name = "Município")]
        [Required(ErrorMessage = "Selecione um Município")]
        public string MunicipioSelecionado { get; set; }

        public List<SelectListItem> Municipios { get; set; }

        public PrevisaoTempoViewModel()
        {
            Estados = new List<SelectListItem>(GetEstados());
            Estados.Insert(0, new SelectListItem() { Text = "(Selecione uma opção)", Value = "" });

            Municipios = new List<SelectListItem>();
            Municipios.Insert(0, new SelectListItem() { Text = "(Selecione uma opção)", Value = "" });
        }

        private List<SelectListItem> GetEstados()
        {
            List<SelectListItem> estados = new List<SelectListItem>()
            {
                 new SelectListItem(){ Text = "AC", Value = "AC"},

                 new SelectListItem(){ Text = "AL", Value = "AL"},

                 new SelectListItem(){ Text = "AP", Value = "AP"},

                 new SelectListItem(){ Text = "AM", Value = "AM"},

                 new SelectListItem(){ Text = "BA", Value = "BA"},

                 new SelectListItem(){ Text = "CE", Value = "CE"},

                 new SelectListItem(){ Text = "ES", Value = "ES"},

                 new SelectListItem(){ Text = "GO", Value = "GO"},

                 new SelectListItem(){ Text = "MA", Value = "MA"},

                 new SelectListItem(){ Text = "MT", Value = "MT"},

                 new SelectListItem(){ Text = "MS", Value = "MS"},

                 new SelectListItem(){ Text = "MG", Value = "MG"},

                 new SelectListItem(){ Text = "PA", Value = "PA"},

                 new SelectListItem(){ Text = "PB", Value = "PB"},

                 new SelectListItem(){ Text = "PR", Value = "PR"},

                 new SelectListItem(){ Text = "PE", Value = "PE"},

                 new SelectListItem(){ Text = "PI", Value = "PI"},

                 new SelectListItem(){ Text = "RJ", Value = "RJ"},

                 new SelectListItem(){ Text = "RN", Value = "RN"},

                 new SelectListItem(){ Text = "RS", Value = "RS"},

                 new SelectListItem(){ Text = "RO", Value = "RO"},

                 new SelectListItem(){ Text = "RR", Value = "RR"},

                 new SelectListItem(){ Text = "SC", Value = "SC"},

                 new SelectListItem(){ Text = "SP", Value = "SP"},

                 new SelectListItem(){ Text = "SE", Value = "SE"},

                 new SelectListItem(){ Text = "TO", Value = "TO"}
            };

            return estados;
        }
    }
}

ApsHgBrasilWeather/Controllers/PrevisaoTempoController.cs
using ApsHgBrasilWeather.Lib.Helpers;
using ApsHgBrasilWeather.Lib.Models.RestModels.HgBrasil;
using ApsHgBrasilWeather.Lib.Models.ViewModels;
using ApsHgBrasilWeather.Lib.Services;
using ApsHgBrasilWeather.Lib.Util;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ApsHgBrasilWeather.Controllers
{
    public class PrevisaoTempoController : Controller
    {
        public ActionResult Index()
        {
            PrevisaoTempoViewModel viewModel = new PrevisaoTempoViewModel();

            return View(viewModel);
        }

        public async Task<ActionResult> GetPrevisaoTempo(string estadoEscolhido, string municipioEscolhido)
        {
            PrevisaoTempoAtualService service = new PrevisaoTempoAtualService();
            string parametros = service.MontarParametros(estadoEscolhido, municipioEscolhido);

            var retorno = await ApiHelper.GetPrevisaoTempoAtual(parametros);

            if (retorno.Sucesso)
            {
                string painel = RazorUtil.GetTemplate(retorno.Resultado);

                return Json(new { OK = retorno.Sucesso, stringHtml = painel }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { OK = false, Mensagem = retorno.Mensagem, }, JsonRequestBehavior.AllowGet);
            }
        }

        public async Task<ActionResult> GetMunicipios(string estadoEscolhido)
        {
            var retorno = await ApiHelper.GetMunicipios(estadoEscolhido);

            if (retorno.Sucesso)
            {
                return Json(new { OK = retorno.Sucesso, Municipios = retorno.Resultado
                    .OrderBy(p => p.Nome).ToList() }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { OK = false}, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

ApsHgBrasilWeather/Views/PrevisaoTempo/Index.cshtml
@model ApsHgBrasilWeather.Lib.Models.ViewModels.PrevisaoTempoViewModel

@using (Html.BeginForm("Index", "PrevisaoTempo", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.EstadoSelecionado, htmlAttributes: new { @class = "control-label col-md-1 campoObrigatorio" })
        <div class="col-md-4">
            @Html.DropDownListFor(model => Model.EstadoSelecionado, Model.Estados, new { @id = "ddlEstados", @class = "form-control", @onchange = $"GetMunicipios('{Url.Action("GetMunicipios", "PrevisaoTempo")}')" })
            @Html.ValidationMessageFor(model => model.EstadoSelecionado, "", new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => model.MunicipioSelecionado, htmlAttributes: new { @class = "control-label col-md-1 campoObrigatorio" })
        <div class="col-md-4">
            @Html.DropDownListFor(model => Model.MunicipioSelecionado, Model.Municipios, new { @id = "ddlMunicipios", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MunicipioSelecionado, "", new { @class = "text-danger" })
        </div>

        <div class="col-md-1">
            <i class="fa fa-search fa-2x btnPesquisar" onclick="Pesquisar('@Url.Action("GetPrevisaoTempo", "PrevisaoTempo")')"></i>
        </div>
    </div>

   
    
    <div id="accordion">
    </div>
</div>

}